[package]
name = "nebulet"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]

[workspace]
members = ["tools"]

[features]
default = ["vga"]
vga = []
serial = []

[dependencies]
spin = "0.4.6"
rlibc = "1.0.0"

[dependencies.x86_64]
git = "https://github.com/Nebulet/x86_64.git"
branch = "rewrite"

[dependencies.os_bootinfo]
git = "https://github.com/Nebulet/os_bootinfo.git"

[dependencies.lazy_static]
version = "1.0.0"
features = ["spin_no_std"]