[package]
name = "nebulet"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]

[workspace]
members = ["tools"]
exclude = [
    "target/x86_64-nebulet/release/bootloader",
    "target/x86_64-nebulet/debug/bootloader",
    "cretonne"
]

[features]
default = ["linked_alloc", "serial"]
vga = []
serial = []
bump_alloc = []
linked_alloc = ["linked_list_allocator"]

[dependencies]
spin = "0.4.6"
rlibc = "1.0.0"
bitflags = "1.0.1"
bit_field = "0.9.0"
hashmap_core = "0.1.2"

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"

[dependencies.x86_64]
git = "https://github.com/Nebulet/x86_64.git"
branch = "rewrite"

[dependencies.os_bootinfo]
git = "https://github.com/Nebulet/os_bootinfo.git"

[dependencies.lazy_static]
version = "1.0.0"
features = ["spin_no_std"]

[dependencies.linked_list_allocator]
version = "0.5.0"
optional = true

[dependencies.nebulet_abi]
path = "nabi"

# Cretonne compiler
[dependencies.cretonne]
path = "cretonne/lib/cretonne"
default-features = false
features = ["no_std"]

[dependencies.cretonne-frontend]
path = "cretonne/lib/frontend"
default-features = false
features = ["no_std"]

[dependencies.cretonne-wasm]
path = "cretonne/lib/wasm"
default-features = false
features = ["no_std"]

[dependencies.cretonne-native]
path = "cretonne/lib/native"
default-features = false
features = ["no_std"]

[dependencies.wasmparser]
git = "https://github.com/nebulet/wasmparser.rs.git"
branch = "no_std"